version: '3.8'

services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/symfony
      - symfony_cache:/var/www/symfony/var
    environment:
      DATABASE_URL: mysql://root:Not24get@mysql:3306/insituBDD?serverVersion=8.0.37
      MONGODB_URL: mongodb://app:Not24get@mongodb:27017/?authSource=InsituBDD
      MONGODB_DB: InsituBDD
      REDIS_URL: redis://redis:6379
      APP_ENV: dev
    depends_on:
      - mysql
      - mongodb
      - redis
    networks:
      - symfony_network

  mysql:
    image: mysql:9.1.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Not24get
      MYSQL_DATABASE: insituBDD
      MYSQL_USER: app
      MYSQL_PASSWORD: Not24get
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_network

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: InsituBDD
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: Not24get
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - symfony_network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - symfony_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - symfony
    networks:
      - symfony_network

volumes:
  mysql_data:
  symfony_cache:
  mongodb_data:
  redis_data:

networks:
  symfony_network:
    driver: bridge
