#
#services:
####> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-16}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#      POSTGRES_USER: ${POSTGRES_USER:-app}
#    healthcheck:
#      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
#      timeout: 5s
#      retries: 5
#      start_period: 60s
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
#      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      # - ./docker/db/data:/var/lib/postgresql/data:rw
####< doctrine/doctrine-bundle ###
#
#volumes:
####> doctrine/doctrine-bundle ###
#  database_data:
####< doctrine/doctrine-bundle ###

version: '3.8'

services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/symfony                 # Monte le code source pour le développement
      - symfony_cache:/var/www/symfony/var  # Volume pour les fichiers de cache Symfony
    environment:
      DATABASE_URL: mysql://root:Not24get@localhost:3306/insituBDD?serverVersion=8.0.37
      APP_ENV: dev
    depends_on:
      - mysql
    networks:
      - symfony_network

  mysql:
    image: mysql:9.1.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Not24get
      MYSQL_DATABASE: insituBDD
      MYSQL_USER: app
      MYSQL_PASSWORD: Not24get
    ports:
      - "3307:3306"       # Pour accéder à MySQL depuis l'hôte
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"       # Expose le port 80 du conteneur sur le port 8080 de l'hôte
    volumes:
      - .:/var/www/symfony           # Monte le code source
      - ./nginx.conf:/etc/nginx/nginx.conf  # Fichier de configuration Nginx
    depends_on:
      - symfony
    networks:
      - symfony_network

volumes:
  mysql_data:
  symfony_cache:

networks:
  symfony_network:
    driver: bridge

